In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import scipy.stats as stats
from scipy.stats import linregress
from matplotlib.dates import DateFormatter

# Read and display the CSV with Pandas
file = "../Desktop/Life Expectancy Data.csv"
df = pd.read_csv(file, encoding="ISO-8859-1")
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8

In [2]:
# Identify incomplete rows
df.count()

Country                            2938
Year                               2938
Status                             2938
Life expectancy                    2928
Adult Mortality                    2928
infant deaths                      2938
Alcohol                            2744
percentage expenditure             2938
Hepatitis B                        2385
Measles                            2938
 BMI                               2904
under-five deaths                  2938
Polio                              2919
Total expenditure                  2712
Diphtheria                         2919
 HIV/AIDS                          2938
GDP                                2490
Population                         2286
 thinness  1-19 years              2904
 thinness 5-9 years                2904
Income composition of resources    2771
Schooling                          2775
dtype: int64

In [3]:
# Identify shape of DataFrame
df.shape

(2938, 22)

In [4]:
# Drop all rows with missing information
clean_df = df.dropna(how='any')
clean_df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8

In [5]:
# Verify dropped rows
clean_df.shape

(1649, 22)

In [6]:
# Verify dropped rows
clean_df.count()

Country                            1649
Year                               1649
Status                             1649
Life expectancy                    1649
Adult Mortality                    1649
infant deaths                      1649
Alcohol                            1649
percentage expenditure             1649
Hepatitis B                        1649
Measles                            1649
 BMI                               1649
under-five deaths                  1649
Polio                              1649
Total expenditure                  1649
Diphtheria                         1649
 HIV/AIDS                          1649
GDP                                1649
Population                         1649
 thinness  1-19 years              1649
 thinness 5-9 years                1649
Income composition of resources    1649
Schooling                          1649
dtype: int64

In [7]:
# Determine the data types of each column.
clean_df.dtypes

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object

In [8]:
# Get a list of all of our columns for easy reference
clean_df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [9]:
# Reorganizing the columns using double brackets
organized_df = clean_df[['Country', 'Year', 'Status',  'Population', 'Life expectancy ', 'Adult Mortality', 
                         'under-five deaths ', 'infant deaths', ' HIV/AIDS', 'Diphtheria ', 'Hepatitis B', 'Measles ', 
                         'Polio', ' thinness 5-9 years', ' thinness  1-19 years', 'Alcohol', ' BMI ', 'GDP', 
                         'percentage expenditure', 'Total expenditure', 'Income composition of resources', 
                         'Schooling']]
organized_df.head()

,Country,Year,Status,Population,Life expectancy,Adult Mortality,under-five deaths,infant deaths,HIV/AIDS,Diphtheria,...,Polio,thinness 5-9 years,thinness 1-19 years,Alcohol,BMI,GDP,percentage expenditure,Total expenditure,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,33736494.0,65.0,263.0,83,62,0.1,65.0,...,6.0,17.3,17.2,0.01,19.1,584.259210,71.279624,8.16,0.479,10.1
1,Afghanistan,2014,Developing,327582.0,59.9,271.0,86,64,0.1,62.0,...,58.0,17.5,17.5,0.01,18.6,612.696514,73.523582,8.18,0.476,10.0
2,Afghanistan,2013,Developing,31731688.0,59.9,268.0,89,66,0.1,64.0,...,62.0,17.7,17.7,0.01,18.1,631.744976,73.219243,8.13,0.470,9.9
3,Afghanistan,2012,Developing,3696958.0,59.5,272.0,93,69,0.1,67.0,...,67.0,18.0,17.9,0.01,17.6,669.959000,78.184215,8.52,0.463,9.8
4,Afghanistan,2011,Developing,2978599.0,59.2,275.0,97,71,0.1,68.0,...,68.0,18.2,18.2,0.01,17.2,63.537231,7.097109,7.87,0.454,9.5

In [10]:
renamed_df = organized_df.rename(columns={"Life expectancy ":"Life Expectancy", 
                                          "under-five deaths ":"Under-Five Deaths", 
                                          "infant deaths":"Infant Deaths", 
                                          " HIV/AIDS":"HIV/AIDS", 
                                          "Diphtheria ":"Diphtheria",
                                          "Measles ":"Measles", 
                                          " thinness 5-9 years":"Thinness 5-9 years", 
                                          " thinness  1-19 years":"Thinness 1-19 years", 
                                          " BMI ":"BMI", 
                                          "percentage expenditure":"Percentage Expenditure", 
                                          "Total expenditure":"Total Expenditure", 
                                          "Income composition of resources":"Income Composition of Resources"})
renamed_df.head()

,Country,Year,Status,Population,Life Expectancy,Adult Mortality,Under-Five Deaths,Infant Deaths,HIV/AIDS,Diphtheria,...,Polio,Thinness 5-9 years,Thinness 1-19 years,Alcohol,BMI,GDP,Percentage Expenditure,Total Expenditure,Income Composition of Resources,Schooling
0,Afghanistan,2015,Developing,33736494.0,65.0,263.0,83,62,0.1,65.0,...,6.0,17.3,17.2,0.01,19.1,584.259210,71.279624,8.16,0.479,10.1
1,Afghanistan,2014,Developing,327582.0,59.9,271.0,86,64,0.1,62.0,...,58.0,17.5,17.5,0.01,18.6,612.696514,73.523582,8.18,0.476,10.0
2,Afghanistan,2013,Developing,31731688.0,59.9,268.0,89,66,0.1,64.0,...,62.0,17.7,17.7,0.01,18.1,631.744976,73.219243,8.13,0.470,9.9
3,Afghanistan,2012,Developing,3696958.0,59.5,272.0,93,69,0.1,67.0,...,67.0,18.0,17.9,0.01,17.6,669.959000,78.184215,8.52,0.463,9.8
4,Afghanistan,2011,Developing,2978599.0,59.2,275.0,97,71,0.1,68.0,...,68.0,18.2,18.2,0.01,17.2,63.537231,7.097109,7.87,0.454,9.5

In [11]:
renamed_df.describe()

,Year,Population,Life Expectancy,Adult Mortality,Under-Five Deaths,Infant Deaths,HIV/AIDS,Diphtheria,Hepatitis B,Measles,Polio,Thinness 5-9 years,Thinness 1-19 years,Alcohol,BMI,GDP,Percentage Expenditure,Total Expenditure,Income Composition of Resources,Schooling
count,1649.000000,1.649000e+03,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000,1649.000000
mean,2007.840509,1.465363e+07,69.302304,168.215282,44.220133,32.553062,1.983869,84.155246,79.217708,2224.494239,83.564585,4.907762,4.850637,4.533196,38.128623,5566.031887,698.973558,5.955925,0.631551,12.119891
std,4.087711,7.046039e+07,8.796834,125.310417,162.897999,120.847190,6.032360,21.579193,25.604664,10085.802019,22.450557,4.653757,4.599228,4.029189,19.754249,11475.900117,1759.229336,2.299385,0.183089,2.795388
min,2000.000000,3.400000e+01,44.000000,1.000000,0.000000,0.000000,0.100000,2.000000,2.000000,0.000000,3.000000,0.100000,0.100000,0.010000,2.000000,1.681350,0.000000,0.740000,0.000000,4.200000
25%,2005.000000,1.918970e+05,64.400000,77.000000,1.000000,1.000000,0.100000,82.000000,74.000000,0.000000,81.000000,1.700000,1.600000,0.810000,19.500000,462.149650,37.438577,4.410000,0.509000,10.300000
50%,2008.000000,1.419631e+06,71.700000,148.000000,4.000000,3.000000,0.100000,92.000000,89.000000,15.000000,93.000000,3.200000,3.000000,3.790000,43.700000,1592.572182,145.102253,5.840000,0.673000,12.300000
75%,2011.000000,7.658972e+06,75.000000,227.000000,29.000000,22.000000,0.700000,97.000000,96.000000,373.000000,97.000000,7.100000,7.100000,7.340000,55.800000,4718.512910,509.389994,7.470000,0.751000,14.000000
max,2015.000000,1.293859e+09,89.000000,723.000000,2100.000000,1600.000000,50.600000,99.000000,99.000000,131441.000000,99.000000,28.200000,27.200000,17.870000,77.100000,119172.741800,18961.348600,14.390000,0.936000,20.700000

In [12]:
renamed_df.to_csv("cleaned_data_output.csv")